Portfolio desktop version
samuelmoiwa/Portfolio-project pull request #1
Opened 2022-08-24 03:02 UTC by samuelmoiwa

## Portfolio Desktop Version

## Solution description
**CSS:** design contents have been added to match the Figma design.
**HTML:** text content and images has been added to the HTML file to match the Figma design
**Form Spree:** add form space link to contact me form, for data submission.
**Linters files:** linters files configured

## Address affected and ensured
* HTML file
* CSS file
* Linters Config
---

2022-08-24 04:23 UTC, mgmediaweb requested changes
Hi  @samuelmoiwa, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost1](https://user-images.githubusercontent.com/41912912/186326910-cef100c9-c7d8-492e-8dfd-fe6d14cf4c4d.gif)

## Highlights 💯 
- Professional README file. ✔️
- PR has a good title and summary. ✔️
- Good design applied. ✔️

## Required Changes ♻️

*** Kindly recommend you create a media query section in your CSS file to differentiate the mobile and desktop view, your site will adapt to each device

*** Kindly recommend you remove excessive blank lines in your HTML file, it will make your site look more professional.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 04:23 UTC, mgmediaweb commented on style.css
> +  padding-top: 105px;
I kindly recommend you to use flexbox to place element at the center of the container (do not use margin-top), with this your website will be more responsive to any device size

2022-08-24 04:23 UTC, mgmediaweb commented on style.css
> +  margin-top: 300px;
I kindly recommend you to use the flexbox functions to place elements at the center of the container (do not use margin-top), with this your website will be more responsive to any device size

2022-08-24 06:43 UTC, Ginohmk requested changes
Hi @samuelmoiwa , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![keep-trying-youre-almost-there](https://user-images.githubusercontent.com/67087664/169483884-c624db70-793d-42be-8ebe-afef6a1cd5c3.gif)

 ## Highlights
- No linters :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 06:43 UTC, Ginohmk commented on style.css
> +  width: 100%;
- Please just as the project requirement stated, you are to use media query in order to get a responsive design. Use **media queries in your CSS  file to make your desktop version look like the template you selected (Desktop: 768px or wider).** This should enable your design to look good on both mobile and Desktop view

##### Your design
![image](https://user-images.githubusercontent.com/58771507/186348493-7cf8e4ed-5287-40bc-aaf6-a2368aa3863d.png)



##### FIgma
![image](https://user-images.githubusercontent.com/58771507/186348689-5de8bf29-47f4-4cd6-ad2b-51f945f97ebe.png)

2022-08-24 17:15 UTC, samuelmoiwa commented on style.css
> +  width: 100%;
hello, I have made the changes, but it has been submitted twice already, I only have one review now. so please cross-check before I do the submission. thanks

2022-08-26 15:13 UTC, RolandM99 approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @samuelmoiwa, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 15:13 UTC, RolandM99 commented on style.css
> +  margin-left: 0;
- [ ] [**OPTIONAL**] To make sure that your style fit exactly the original design from Figma, I'll suggest you to implement your button interactions such as hover, active (when it's pressed), disabled, and enable (default state) styled as shown in the Figma template. check the screenshot below:
![image](https://user-images.githubusercontent.com/71874425/186142037-41a9e629-218f-4ab5-9f54-cf90ae740945.png)

2022-08-26 18:53 UTC, merged